import './globals.css'
import { Inter } from 'next/font/google'
import React, { ReactNode } from 'react'
import Link from 'next/link'
import StyledComponentsRegistry from '@app/_lib/registry'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StyledComponentsRegistry>
          <nav>
            <Link href="/">Home</Link>
            <Link href="/products">Products</Link>
          </nav>
          {children}
        </StyledComponentsRegistry>
      </body>
    </html>
  )
}
