import './globals.css'
import { Inter } from 'next/font/google'
import { ReactNode } from 'react'
import { Header } from '@app/components/Header'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body
        className={
          (inter.className, 'w-full max-w-7xl mx-auto px-1 md:px-2 2xl:px-0')
        }
      >
        <Header />
        {children}
      </body>
    </html>
  )
}
