import '@/public/styles/globals.css'
import { Inter } from 'next/font/google'
import type { AppProps } from 'next/app'
import { Header } from '@components/Header'
import StyledComponentsRegistry from '@/src/lib/registry'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function App({ Component, pageProps }: AppProps) {
  return (
    <StyledComponentsRegistry>
      <main className="bg-slate-950">
        <section
          className={
            (inter.className, 'w-full max-w-7xl mx-auto px-1 md:px-2 2xl:px-0')
          }
        >
          <Header />
          <Component {...pageProps} />
        </section>
      </main>
    </StyledComponentsRegistry>
  )
}
