import '@/public/styles/globals.css'
import { Inter } from 'next/font/google'
import type { AppProps } from 'next/app'
import { Header } from '@components/Header'
import StyledComponentsRegistry from '@/src/lib/registry'
import { ApolloProvider } from '@apollo/client'
import { apolloClient } from '@lib/apollo-client.config'
import { Layout } from '@components/Layout'
import { hasHydrated } from '@util/has-hydrated.hook'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function App({ Component, pageProps }: AppProps) {
  const hasMounted = hasHydrated()

  return hasMounted ? (
    <StyledComponentsRegistry>
      <ApolloProvider client={apolloClient}>
        <Layout className={inter.className}>
          <Header />
          <Component {...pageProps} />
        </Layout>
      </ApolloProvider>
    </StyledComponentsRegistry>
  ) : null
}
